name: "[Workflow] Deploy"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test_job.yml

  build_deploy:
    name: Build and Deploy
    needs: ['test']
    uses: ./.github/workflows/deploy_job.yml
