name: "[Workflow] PR Build"

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test_job.yml

  publish_unit_tests:
    name: Publish Unit Tests
    needs: ['test']
    uses: ./.github/workflows/publish_unit_tests.yml

  dependabot:
    name: Dependabot Approve and Auto Merge
    needs: ['test']
    uses: ./.github/workflows/dependabot-approve-and-auto-merge_job.yml
