on:
  workflow_call:

jobs:
  publish_unit_tests:
    name: Publish Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Download Clover Artifact
        id: download_clover
        uses: actions/download-artifact@v4
        with:
          name: clover
          path: coverage/clover.xml

      - name: Coverage Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: "coverage/clover.xml"
          min-line-coverage: 5
          min-method-coverage: 5
